# Generated by Django 4.1.7 on 2023-03-19 08:15

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealisationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('photo', django_resized.forms.ResizedImageField(crop=['top', 'left'], default='default_tall.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[370, 250], upload_to='work')),
                ('maitre_douvrage', models.CharField(max_length=500)),
                ('architecte', models.CharField(max_length=500)),
                ('livraison', models.DateField()),
                ('montant_travaux', models.CharField(max_length=100)),
                ('specificite_technique', models.CharField(max_length=500)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Realisation',
                'ordering': ['-livraison'],
            },
        ),
    ]
