# Generated by Django 4.1.7 on 2023-03-18 12:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='blog/posts/', verbose_name='Post Image')),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('posttags', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags')),
                ('post_Slug', models.SlugField(allow_unicode=True, blank=True, max_length=500, null=True, unique=True, verbose_name='Slugfiy')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
    ]
