# Generated by Django 4.1.7 on 2023-03-18 13:34

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValeurPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('photo', django_resized.forms.ResizedImageField(crop=['top', 'left'], default='default_tall.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[288, 146], upload_to='work')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Valeurs',
            },
        ),
    ]
